name: Test Data Pipeline CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository step by step
      uses: actions/checkout@v2

    - name: Set up Python in the system
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install all the dependencies that needed
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
        
    - name: Run the test File
      run: |
        chmod +x project/tests.sh
        project/tests.sh
